apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cloud-infrastructure
    name: config-service
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-infrastructure
      name: config-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: cloud-infrastructure
        name: config-service
    spec:
      containers:
      - image: nimbleplatform/config-service
        imagePullPolicy: Always
        name: config-service
        ports:
        - containerPort: 9096
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi