##########################
#### MS Infrastructure ###
##########################

config-server:
  image: nimbleplatform/config-server
  env_file:
    - env_vars
  ports:
    - "8888:8888"
#  links:
#    - logstash

service-discovery:
  image: nimbleplatform/service-discovery
  env_file:
    - env_vars
  ports:
    - "8761:8761"
  links:
    - config-server
#    - logstash

gateway-proxy:
  image: nimbleplatform/gateway-proxy
  env_file:
    - env_vars
  ports:
    - "10001:80"
  links:
    - config-server
    - service-discovery
#    - logstash

hystrix-dashboard:
  image: nimbleplatform/hystrix-dashboard
  env_file:
    - env_vars
  ports:
    - "9080:9080"
  links:
    - config-server
    - service-discovery
#    - logstash
#
###########################
######## ELK Stack ########
###########################
#
#elasticsearch:
#  image: elasticsearch:latest
#  ports:
#    - "9200:9200"
#    - "9300:9300"
#
#logstash:
#  build: elk/logstash/
#  command: logstash -f /etc/logstash/conf.d/logstash.conf
#  volumes:
#    - ./elk/logstash/config:/etc/logstash/conf.d
#  ports:
#    - "5000:5000"
#  links:
#    - elasticsearch
#
#kibana:
#  build: elk/kibana/
#  volumes:
#    - ./elk/kibana/config/:/opt/kibana/config/
#  ports:
#    - "5601:5601"
#  links:
#    - elasticsearch