config-server:
  image: nimbleplatform/config-server
  env_file:
    - env_vars
  ports:
   - "8888:8888"

service-discovery:
  image: nimbleplatform/service-discovery
  env_file:
    - env_vars
  ports:
    - "8761:8761"
  links:
   - config-server

proxy-server:
  image: nimbleplatform/proxy-server
  env_file:
    - env_vars
  ports:
    - "10001:80"
  links:
   - config-server
   - service-discovery

hystrix-dashboard:
  image: nimbleplatform/hystrix-dashboard
  env_file:
    - env_vars
  ports:
    - "9080:9080"
  links:
   - config-server
   - service-discovery