version: '2'

services:
  ##########################
  #### MS Infrastructure ###
  ##########################

  config-server:
    image: nimbleplatform/config-server
    env_file:
      - env_vars
    ports:
      - "8888:8888"
    networks:
      - test

  service-discovery:
    image: nimbleplatform/service-discovery
    env_file:
      - env_vars
    ports:
      - "8761:8761"
    links:
      - config-server
    networks:
      - test

  gateway-proxy:
    image: nimbleplatform/gateway-proxy
    env_file:
      - env_vars
    ports:
      - "8080:80"
    links:
      - config-server
      - service-discovery
    networks:
      - test

  hystrix-dashboard:
    image: nimbleplatform/hystrix-dashboard
    env_file:
      - env_vars
    ports:
      - "9080:9080"
    links:
      - config-server
      - service-discovery
    networks:
      - test

  ###########################
  ######## ELK Stack ########
  ###########################

  elasticsearch:
    build: elk/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - test

  logstash:
    build: elk/logstash/
    volumes:
      - ./elk/logstash/log:/var/log/logstash
    ports:
      - "5000:5000"
    links:
      - elasticsearch
    networks:
      - test

  kibana:
    build: elk/kibana/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - test

networks:
  test:
    driver: bridge