spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nimble-platform/cloud-config
encrypt:
  keyStore:
    location: classpath:/configserver.jks
    password: password
    alias: nimbleconfigkey
    secret: secret